services:
  - type: web
    name: crane-prize-server
    env: python
    plan: free
    buildCommand: ./build.sh
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.2
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright
